### ISSUE TITLE
Open Task check misses checked tasks

### ISSUE THREAD

**Issue by BGehrels** [zalando/zappr#510] opened 2017-06-15 12:49 UTC
Given an existing PR and
given you've activated the zappr/pr/tasks check
when you've edited it's first comment to include a task list with one element
then zappr correctly blocks the PR.

Given the above,
when you click on the checkbox for the task
then zappr some times still blocks the pr saying "zappr/pr/tasks — PR has 1 open tasks."

**Comment by BGehrels** [comment] 2017-06-15 13:21
The last webhook transmission contains the checked task list entry in `$.issue.body`:
> "The current code ANONYMIZED then).\r\n\r\n- [x] Implement ANONYMIZED alarms (and ANONYMIZED data) are ANONYMIZED."

**Comment by harti2006** [comment] 2017-06-15 13:41
I can confirm the bug. It is definitely related to the current issue with GitHub Enterprise sending the wrong pull request body with the webhook.

However in this case it is also suspicious that the "body" attribute is below "issue" instead of "pull_request".

**Comment by harti2006** [comment] 2017-09-20 13:06
This issue is fixed now, since Github sends the correct webhook payload again.

**Closed** 2017-09-20 13:18 UTC
Labels: bug
