### ISSUE TITLE
Consider reducing the number of required GitHub permissions

### ISSUE THREAD

**Issue by hjacobs** [zalando/zappr#235] opened 2016-04-22 09:36 UTC
Zappr currently requires write access to repos and admin access to hooks/services --- I don't really want to grant this "god mode" access to get PR approval checks with Zappr.

Is there a way of reducing the number of required permissions? I would personally like to only give read access where needed. I definitely want to prevent 3rd party apps to have write access to my code..

![zappr-consent](https://cloud.githubusercontent.com/assets/510328/14737749/fc632f8a-087d-11e6-933d-3bbdfcefeb91.png)

**Comment by prayerslayer** [comment] 2016-04-22 09:46
Currently not, sorry, but we explain why we need those scopes [in our FAQ](http://zappr.readthedocs.org/en/latest/faq/#why-do-you-need-these-scopes).

Maybe we can introduce a toggle to switch between "minimal" and "god" mode. But we have to think this through.

Closing because it's a duplicate of https://github.com/zalando/zappr/issues/90

**Closed by prayerslayer** 2016-04-22 09:46 UTC

**Comment by hjacobs** [comment] 2016-04-22 09:49
@prayerslayer ok, sorry for the duplicate --- I searched before creating the issue, but only for "permission" :smirk:

**Comment by prayerslayer** [comment] 2016-04-22 09:55
Ya we should probably rename it because it's not only about repo.write.
